# -*- coding: utf-8 -*-
"""Image_Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1clynmILRx04lOTi234NBHwHMWHxdMcHt

#Libraries
"""

import os
import cv2
import numpy as np

"""# Remove_noise function
 It preprocess the images to reduce the noises in the images to be prepared for detection model
"""

def remove_noise(img):
    # Apply median blur to remove salt and pepper noise
    img_median = cv2.medianBlur(img, 5)

    # Apply Gaussian blur to remove Gaussian noise
    img_gaussian = cv2.GaussianBlur(img_median, (5, 5), 0)


    return img_gaussian

def preprocess_images(input_folder, output_folder):
    # Create the output folder if it doesn't exist
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # Get a list of all image files in the input folder
    image_files = os.listdir(input_folder)

    for image_file in image_files:
        # Read the image
        image_path = os.path.join(input_folder, image_file)
        img = cv2.imread(image_path)

        # Check if the image was successfully read
        if img is not None:
            # Preprocess the image
            processed_img = remove_noise(img)

            # Save the processed image in the output folder
            output_path = os.path.join(output_folder, image_file)
            cv2.imwrite(output_path, processed_img)
            print(f"Processed image saved: {output_path}")
        else:
            print(f"Error reading image: {image_path}")

# Usage example
input_folder = '/content/input'
output_folder = '/content/output'
preprocess_images(input_folder, output_folder)